In [2]:
import numpy as np

In [12]:
print("Rank 1 array with 3 elements")
a=np.array([1,2,3])
print(a)
a.shape

Rank 1 array with 3 elements
[1 2 3]


(3,)

In [6]:
print("Rank 2 array with 2 rows and 3 coloumn")
a=np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

Rank 2 array with 2 rows and 3 coloumn
[[1 2 3]
 [4 5 6]]


(2, 3)

In [10]:
print("Rank 3 array with 1 block, 2 rows and 3 coloumn")
a=np.array([[[1,2,3],[4,5,6]]])
print(a)
a.shape

Rank 3 array with 1 block, 2 rows and 3 coloumn
[[[1 2 3]
  [4 5 6]]]


(1, 2, 3)

In [31]:
print("Rank 3 array with 2 blocks, 2 rows and 3 coloumn")
a=np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])
print(a)
a.shape

Rank 3 array with 2 blocks, 2 rows and 3 coloumn
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

In [32]:
print("type",type(a))

type <class 'numpy.ndarray'>


In [14]:
print("Identity Matrix(4*4)")
a=np.eye(4)
print(a)

Identity Matrix(4*4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
print("All zeroes array with 2 rows and 3 cols")
a=np.ones((2,3))
print(a)

All zeroes array with 2 rows and 3 cols
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print("All zeroes array with 3 rows and 3 cols")
a=np.ones((3,3))
print(a)

All zeroes array with 3 rows and 3 cols
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print("Random Matrix")
a=np.random.random((2,2,))
print(a)

Random Matrix
[[0.9186528  0.24741379]
 [0.95422125 0.5170802 ]]


In [22]:
a=np.array([[1,2],[3,4]])
print("Total Sum:",np.sum(a))

Total Sum: 10


In [26]:
a=np.array([[1,2],[3,4]])
print("Axis wise sum:",np.sum(a,axis=0))
print("Coordinate wise sum:",np.sum(a,axis=1))

Axis wise sum: [4 6]
Coordinate wise sum: [3 7]


In [29]:
a=np.arange(1000)
b=np.arange(1000)
print("Dot Product",np.dot(a,b))

Dot Product 332833500


In [30]:
print("Element wise Product",np.multiply(a,b))

Element wise Product [     0      1      4      9     16     25     36     49     64     81
    100    121    144    169    196    225    256    289    324    361
    400    441    484    529    576    625    676    729    784    841
    900    961   1024   1089   1156   1225   1296   1369   1444   1521
   1600   1681   1764   1849   1936   2025   2116   2209   2304   2401
   2500   2601   2704   2809   2916   3025   3136   3249   3364   3481
   3600   3721   3844   3969   4096   4225   4356   4489   4624   4761
   4900   5041   5184   5329   5476   5625   5776   5929   6084   6241
   6400   6561   6724   6889   7056   7225   7396   7569   7744   7921
   8100   8281   8464   8649   8836   9025   9216   9409   9604   9801
  10000  10201  10404  10609  10816  11025  11236  11449  11664  11881
  12100  12321  12544  12769  12996  13225  13456  13689  13924  14161
  14400  14641  14884  15129  15376  15625  15876  16129  16384  16641
  16900  17161  17424  17689  17956  18225  18496  18769