In [1]:
import numpy as np

In [2]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
a=np.ones([1,2,3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
a=np.zeros([1,2,3])
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
a=np.array([[1,2,3,4],[1,2,3,4]])
print(a.shape)

(2, 4)


In [10]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
print("type %s"%type(a))

type <class 'numpy.ndarray'>


In [14]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]
